title:Portfolio
author: "Manideep Paduchuri"
email: paduchurimanideep@gmail.com
description: >-
  A minimal, fast, and scalable portfolio showcasing my skills, tools, and code.
theme: minima
header_pages:
  - index.md
  - tools.md
